// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJfH1-FrwDt2eaZl085iBuouiBdfvEqhE',
    appId: '1:643489866555:web:0e45982401e8bb0aea8d1e',
    messagingSenderId: '643489866555',
    projectId: 'sloopify-e1e84',
    authDomain: 'sloopify-e1e84.firebaseapp.com',
    storageBucket: 'sloopify-e1e84.firebasestorage.app',
    measurementId: 'G-ZBLR4G6RB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtin86wyGG_uL4kXFhYok7LONiIQwZnUs',
    appId: '1:643489866555:android:f91efa2e5b005505ea8d1e',
    messagingSenderId: '643489866555',
    projectId: 'sloopify-e1e84',
    storageBucket: 'sloopify-e1e84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvBg25s6bN8F9JWEcUjgdyXqCQ2gUM7UE',
    appId: '1:643489866555:ios:ce94d55e935ed104ea8d1e',
    messagingSenderId: '643489866555',
    projectId: 'sloopify-e1e84',
    storageBucket: 'sloopify-e1e84.firebasestorage.app',
    iosBundleId: 'com.example.sloopifyMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvBg25s6bN8F9JWEcUjgdyXqCQ2gUM7UE',
    appId: '1:643489866555:ios:ce94d55e935ed104ea8d1e',
    messagingSenderId: '643489866555',
    projectId: 'sloopify-e1e84',
    storageBucket: 'sloopify-e1e84.firebasestorage.app',
    iosBundleId: 'com.example.sloopifyMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJfH1-FrwDt2eaZl085iBuouiBdfvEqhE',
    appId: '1:643489866555:web:6ae8290f33ed5bffea8d1e',
    messagingSenderId: '643489866555',
    projectId: 'sloopify-e1e84',
    authDomain: 'sloopify-e1e84.firebaseapp.com',
    storageBucket: 'sloopify-e1e84.firebasestorage.app',
    measurementId: 'G-Z9NVXYGPW3',
  );
}
